-Add Teachers Base
sexfoil/goit-markup-final-project pull request #7
Opened 2023-08-29 18:45 UTC by codajoker

1. Added image for section teacher 
2. Added base markup teacher section 
3. Added padding for mobile container IMPORTANT
4. Added style for mobile device section teacher

2023-08-29 19:42 UTC, sexfoil requested changes

2023-08-29 19:42 UTC, sexfoil commented on src/css/base/container.css
> +    padding-right: 20px;
Загальні стилі такі як 'container' і 'section' не варто змінювати, щоб не викликати конфліктів з іншими секціями інших розробників.

2023-08-29 19:42 UTC, sexfoil commented on src/css/layout/teachers.css
> +.teachers__descriptions {
В назвах класів домовились притримуватися стилю "kebab-case" тобто 
.teachers-list-item {
те саме в інших назвах необхідно передивитися.

2023-08-29 19:42 UTC, sexfoil commented on src/partials/sections/teachers.html
>    <div class="container">
Класи "section" та "container" є обов'язковими та не змінними, як і їх стилі. Краще вказати свій клас "teachers" як додатковий до "section".

2023-08-29 19:42 UTC, sexfoil commented on src/css/layout/teachers.css
Домовились робити різними тасками:
1. Розмітка
2. Стилі для мобільного
3. Адаптив для таблет та десктоп

Відповідно повинно бути 3 окремих ПР для кожної таски (додавати щось додаткове до ПРа це пагана практика).

2023-08-30 13:13 UTC, fff500 commented on src/css/layout/teachers.css
> +  line-height: 1.7; /* 171.429% */
Те, що після крапки з комою потрібно видалити.

2023-08-31 20:05 UTC, closed without merging

2023-08-31 20:05 UTC, sexfoil commented
No needed anymore